In [1]:
import pandas as pd
import os
import openpyxl
import numpy as np
import re

In [2]:
class FinancialReport():
    def __init__(self,file):
        self.file = file
        self.readFile()
        self.findBalanceSheet()
    def readFile(self):
        path = os.path.join("financial statements",self.file)
        self.statements = pd.read_excel(path,sheet_name=None)
    def getSheetNames(self):
        return self.statements.keys()
    def findBalanceSheet(self):
        balanceSheetName = [name for name in self.getSheetNames() if "BALANCE" in name][0]
        self.balance = self.statements[balanceSheetName]
        self.balance.columns = ["labels"]+list(self.balance.columns[1:])
    def getBalanceSheet(self):
        return self.balance

In [34]:
class Balance():
    def __init__(self):
        self.finalBalance = pd.DataFrame(columns=["title","num_title","labels"])
        self.setFinancialStatements()
        self.addDataToBalanceSheet()
        #self.rearrangeFinalBalanceSheet()
        
    def getFiles(self):
        files = os.listdir("financial statements")
        files.remove(".DS_Store")
        files = [file for file in files if file[0] != "~"]
        return files

    def setFinancialStatements(self):
        self.files = self.getFiles()
        self.FinancialReports = [FinancialReport(file) for file in self.files]
        self.addDataToBalanceSheet()
        self.rearrangeFinalBalanceSheet()
        
    def addDataToBalanceSheet(self):
        
        for FinancialStatements in self.FinancialReports[:1]:
            balance = FinancialStatements.getBalanceSheet().copy()
            
            cols = ["labels"]+[col for col in balance.columns[1:] if col not in self.finalBalance.columns] ## remove columns of data already in main balance sheet
            balance = balance[cols]
            
            balance = self.parse_attributes(balance)
            
            balance.loc[:,"labels"] = [re.sub(" \$|\s*\d+\,*", "", label)  if np.any([char.isdigit() for char in label]) else label for label in balance["labels"]  ]
            balance.labels = balance.labels.apply(self.clean_up_string)
            
            
            self.finalBalance = pd.merge(self.finalBalance, balance, how="outer",on=["labels"],suffixes=('', '_new'))

            self.finalBalance.title = [self.finalBalance.title[i] if not pd.isnull(self.finalBalance.title[i]) else self.finalBalance.title_new[i] for i in range(len(self.finalBalance))] #merge titles
            self.finalBalance.num_title = [self.merge_number(self.finalBalance.num_title[i],self.finalBalance.num_title_new[i]) for i in range(len(self.finalBalance))] #merge the number for the titles. use greatest num bc bigger num means there is section before it
            self.finalBalance = self.finalBalance.drop(["title_new","num_title_new"],axis=1)

    def rearrangeFinalBalanceSheet(self):
        self.finalBalance = self.finalBalance.replace(" ",np.nan)

        # put totals at the bottom of each section
        totals = self.finalBalance.loc[self.finalBalance.labels.str.startswith("Total")].reset_index(drop=True) 
        self.finalBalance = self.finalBalance.loc[~self.finalBalance.labels.str.startswith("Total")].reset_index(drop=True)
        self.finalBalance = pd.concat([self.finalBalance,totals]) 
        self.finalBalance = self.finalBalance.reset_index(drop=True).reset_index()
        self.finalBalance = self.finalBalance.sort_values(["num_title","index"])
        

    def parse_attributes(self,balance):
        num = 0
        index = []
        for label in balance.labels:
            if ":" in label:
                title = label[:-1]
                num += 1
                continue
            index.append([title,num,label])
            if "Total" in label:
                title = np.nan
                num += 1

        balance = balance.loc[balance.labels.isin(np.array(index)[:,2])].copy()
        balance.loc[:,["title","num_title","labels"]] = list(index)
        balance = balance.set_index(["title","num_title","labels"]).reset_index()
        return balance
    
    def clean_up_string(self,string):
        string = string.strip()
        space_positions = [x.start() for x in re.finditer('\ ',  string)]
        for i in reversed(space_positions):
            if string[i+1:] in ["of", "and"]:
                string = string[:i]
        return string
    
    def merge_number(self,a,b):
        if pd.isnull(a):
            return b
        if pd.isnull(b):
            return a
        return max(a,b)

In [35]:
balance = Balance()
balance.finalBalance

MergeError: Can only pass argument "on" OR "left_index" and "right_index", not a combination of both.

In [655]:
#cols = finalBalance.columns[2:]

#finalBalance = finalBalance.loc[~finalBalance[cols].isnull().all(axis=1)]

In [656]:
finalBalance = finalBalance.replace(" ",np.nan)

# put totals at the bottom of each section
totals = finalBalance.loc[finalBalance.labels.str.startswith("Total")].reset_index(drop=True) 
finalBalance = finalBalance.loc[~finalBalance.labels.str.startswith("Total")].reset_index(drop=True)
finalBalance = pd.concat([finalBalance,totals]) 
finalBalance = finalBalance.reset_index(drop=True).reset_index()
finalBalance = finalBalance.sort_values(["num_title","index"])

In [657]:
finalBalance2 = finalBalance.drop(["index","num_title"],axis=1)

In [658]:
finalBalance2.to_csv("finalBalance.csv")

In [620]:
finalBalance

,index,title,num_title,labels,"Oct. 30, 2021","Jan. 30, 2021","Oct. 31, 2020","Feb. 01, 2020","Nov. 02, 2019","May 04, 2019",...,"May 05, 2018","Jul. 31, 2021","Aug. 01, 2020","Aug. 03, 2019","Feb. 03, 2018","May 01, 2021","May 02, 2020","Aug. 04, 2018","Jan. 29, 2022","Nov. 03, 2018"
0,0,Current assets,0.0,Cash and cash equivalents,801.0,1988.0,2471.0,1364.0,788.0,941.0,...,1210.0,2375.0,2188.0,1177.0,1783.0,2066.0,1028.0,1322.0,877.00,958.0
1,1,Current assets,0.0,Short-term investments,275.0,410.0,178.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
2,2,Current assets,0.0,Merchandise inventory,2721.0,2451.0,2747.0,2156.0,2720.0,2242.0,...,2035.0,2281.0,2242.0,2326.0,1997.0,2370.0,2217.0,2202.0,3018.00,2668.0
3,3,Current assets,0.0,Other current assets,1410.0,1159.0,966.0,706.0,770.0,757.0,...,778.0,1201.0,882.0,770.0,788.0,1091.0,920.0,780.0,1270.00,792.0
23,23,Current assets,0.0,"Available-for-sale Securities, Current",NaN,NaN,NaN,290.0,294.0,272.0,...,164.0,337.0,25.0,294.0,NaN,475.0,51.0,286.0,NaN,296.0
25,25,Current assets,0.0,Short-term Investments,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
37,37,Current assets,0.0,"Cash and Cash Equivalents, at Carrying Value",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,38,Current assets,0.0,"Other Assets, Current",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40,Current assets,0.0,Total current assets,5207.0,6008.0,6362.0,4516.0,4572.0,4212.0,...,4187.0,6194.0,5337.0,4567.0,4568.0,6002.0,4216.0,4590.0,5165.00,4714.0
4,4,NaN,1.0,"Property and equipment, net of accumulated dep...",2924.0,2841.0,2846.0,3122.0,3225.0,3129.0,...,2791.0,2897.0,2895.0,3141.0,2805.0,2839.0,2945.0,2832.0,3037.00,2887.0
5,5,NaN,1.0,"Operating Lease, Right-of-Use Asset",3788.0,4217.0,4460.0,5402.0,5796.0,5732.0,...,0.0,3975.0,4689.0,5807.0,NaN,4060.0,4851.0,0.0,NaN,0.0
6,6,NaN,1.0,Other long-term assets,861.0,703.0,705.0,639.0,525.0,547.0,...,607.0,693.0,795.0,528.0,616.0,703.0,698.0,588.0,884.00,572.0
31,31,NaN,1.0,"Accumulated Depreciation, Depletion and Amorti...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5071.00,NaN
32,32,NaN,1.0,Operating lease assets,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3675.00,NaN
41,41,NaN,1.0,Total assets,12780.0,13769.0,14373.0,13679.0,14118.0,13620.0,...,7585.0,13759.0,13716.0,14043.0,7989.0,13604.0,12710.0,8010.0,12761.00,8173.0
7,7,Current liabilities,2.0,Accounts payable,1630.0,1743.0,2284.0,1174.0,1241.0,994.0,...,1072.0,1583.0,1629.0,1246.0,1181.0,1530.0,971.0,1297.0,1951.00,1299.0
8,8,Current liabilities,2.0,Accrued expenses and other current liabilities,1414.0,1276.0,1283.0,1067.0,974.0,882.0,...,975.0,1252.0,1124.0,908.0,1270.0,1294.0,1051.0,1026.0,1367.00,1070.0
9,9,Current liabilities,2.0,"Operating Lease, Liability, Current",746.0,831.0,823.0,920.0,934.0,929.0,...,0.0,789.0,856.0,946.0,NaN,798.0,886.0,0.0,NaN,0.0
10,10,Current liabilities,2.0,Income taxes payable,33.0,34.0,41.0,48.0,43.0,26.0,...,11.0,27.0,40.0,34.0,10.0,16.0,23.0,18.0,25.00,24.0
29,29,NaN,2.0,"Line of Credit Facility, Fair Value of Amount ...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,500.0,NaN,NaN,NaN
30,30,Current liabilities,2.0,Current maturities of debt,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,33,Current liabilities,2.0,Current portion of operating lease liabilities,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,734.00,NaN
39,39,Current liabilities,2.0,"Accrued Liabilities, Current",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,42,Current liabilities,2.0,Total current liabilities,3823.0,3884.0,4431.0,3209.0,3192.0,2831.0,...,2058.0,3651.0,3649.0,3134.0,2461.0,3638.0,3431.0,2341.0,4077.00,2393.0
26,26,Long-term liabilities,3.0,Long-term debt,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1249.0,NaN,NaN,NaN,1484.00,NaN
34,34,Long-term liabilities,3.0,Long-term operating lease liabilities,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4033.00,NaN
35,35,Long-term liabilities,3.0,Other long-term liabilities,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,445.00,NaN
43,43,Long-term liabilities,3.0,Total long-term debt,1484.0,2216.0,2214.0,1249.0,1249.0,1249.0,...,1249.0,2220.0,2212.0,1249.0,NaN,2218.0,1250.0,1249.0,NaN,1249.0
11,11,Long-term liabilities,4.0,"Operating Lease, Liability, Noncurrent",4163.0,4617.0,4899.0,5508.0,5650.0,5597.0,...,0.0,4348.0,5179.0,5644.0,NaN,4449.0,5331.0,0.0,NaN,0.0
12,12,Long-term liabilities,4.0,Lease incentives and other long-term liabilities,523.0,438.0,458.0,397.0,393.0,372.0,...,1081.0,520.0,423.0,391.0,1135.0,493.0,381.0,1080.0,NaN,1091.0
27,27,Stockholders' equity,4.0,"Common stock. par value, Authorized shares for...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN
28,28,Stockholders' equity,4.0,Accumulated other comprehensive income,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,36.0,NaN,NaN,NaN,38.00,NaN
36,36,Stockholders' equity,4.0,"Common stock. par value, Authorized shares for...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.00,NaN
44,44,Long-term liabilities,4.0,Total long-term liabilities,6170.0,7271.0,7571.0,7154.0,7292.0,7218.0,...,2330.0,7088.0,7814.0,7284.0,2384.0,7160.0,6962.0,2329.0,5962.00,2340.0
13,13,NaN,5.0,Commitments and contingencies (see Note),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,NaN,5.0,"Common stock, shares outstanding (in shares)",374000.0,374000.0,374000.0,371000.0,373000.0,NaN,...,NaN,376000.0,374000.0,NaN,NaN,377000.0,373000.0,NaN,371000.00,NaN
15,15,Stockholders' equity,5.0,Authorized shares for all periods presented,19.0,19.0,19.0,NaN,NaN,NaN,...,NaN,19.0,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,Stockholders' equity,5.0,Additional Paid in Capital,71.0,85.0,60.0,0.0,0.0,0.0,...,0.0,114.0,39.0,0.0,8.0,118.0,17.0,0.0,43.00,0.0
17,17,Stockholders' equity,5.0,Retained earnings,2681.0,2501.0,2268.0,3257.0,3573.0,3495.0,...,3127.0,2879.0,2173.0,3551.0,3081.0,2667.0,2235.0,3268.0,2622.00,3368.0
18,18,Stockholders' equity,5.0,Amounts reclassified from accumulated other co...,16.0,9.0,24.0,40.0,42.0,57.0,...,51.0,8.0,22.0,55.0,NaN,2.0,46.0,53.0,NaN,53.0
24,24,Stockholders' equity,5.0,Authorized shares for all periods presented; I...,NaN,NaN,NaN,19.0,19.0,19.0,...,19.0,NaN,NaN,19.0,NaN,19.0,19.0,19.0,NaN,19.0
45,45,Stockholders' equity,5.0,Total stockholders' equity,2787.0,2614.0,2371.0,3316.0,3634.0,3571.0,...,3197.0,3020.0,2253.0,3625.0,3144.0,2806.0,2317.0,3340.0,2722.00,3440.0
46,46,NaN,6.0,Total liabilities and stockholders' equity,12780.0,13769.0,14373.0,13679.0,14118.0,13620.0,...,7585.0,13759.0,13716.0,14043.0,7989.0,13604.0,12710.0,8010.0,12761.00,8173.0
19,19,NaN,7.0,"Property and equipment, accumulated depreciation",5486.0,5608.0,5891.0,5839.0,5999.0,NaN,...,NaN,5603.0,5933.0,NaN,NaN,5616.0,5886.0,NaN,NaN,NaN
20,20,NaN,7.0,"Common stock, shares issued (in shares)",374000.0,374000.0,374000.0,371000.0,373000.0,NaN,...,NaN,376000.0,374000.0,NaN,NaN,377000.0,373000.0,NaN,371000.00,NaN
21,21,NaN,7.0,"Common stock, shares authorized (in shares)",2300000.0,2300000.0,2300000.0,2300000.0,2300000.0,NaN,...,NaN,2300000.0,2300000.0,NaN,NaN,2300000.0,2300000.0,NaN,2300000.00,NaN
22,22,NaN,7.0,"Common stock, par value (in dollars per share)",50000.0,50000.0,50000.0,50000.0,50000.0,NaN,...,NaN,50000.0,50000.0,NaN,NaN,50000.0,50000.0,NaN,0.05,NaN